# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recommendation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from Recommendation_System.collaborative_filtering import GroceryRecommendation
from Recommendation_System.user import return_users
from comparison_system import price_comparison

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1205, 713)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setStyleSheet("background-color: rgb(241, 245, 244);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 90, 1211, 71))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.search_bar = QtWidgets.QTextEdit(self.frame)
        self.search_bar.setGeometry(QtCore.QRect(40, 20, 911, 41))
        self.search_bar.setStyleSheet("background-color: rgb(241, 245, 244);\n"
"font: 12pt \"Arial\";\n"
"border: 1px solid; border-radius:20px; border-color:#ffffff;\n"
"")
        self.search_bar.setObjectName("search_bar")
        self.search_button = QtWidgets.QPushButton(self.frame)
        self.search_button.setGeometry(QtCore.QRect(962, 17, 171, 41))
        self.search_button.setStyleSheet("background-color: rgb(191, 163, 255);\n"
"font: 75 12pt \"Arial\";\n"
"color:white;\n"
"border-radius:20px;")
        self.search_button.setObjectName("search_button")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(40, 180, 541, 201))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(170, 10, 181, 31))
        self.label_2.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 181, 31))
        self.label_5.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 181, 31))
        self.label_6.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.product1 = QtWidgets.QLabel(self.frame_2)
        self.product1.setGeometry(QtCore.QRect(130, 50, 401, 31))
        self.product1.setStyleSheet("font: 75 10pt \"Leelawadee\";")
        self.product1.setObjectName("product1")
        self.price1 = QtWidgets.QLabel(self.frame_2)
        self.price1.setGeometry(QtCore.QRect(130, 130, 181, 31))
        self.price1.setStyleSheet("font: 75 10pt \"Leelawadee\";")
        self.price1.setObjectName("price1")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(610, 180, 541, 201))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);border-radius:20px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(210, 10, 181, 31))
        self.label_3.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 181, 31))
        self.label_7.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(20, 130, 181, 30))
        self.label_8.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_8.setObjectName("label_8")
        self.product2 = QtWidgets.QLabel(self.frame_3)
        self.product2.setGeometry(QtCore.QRect(130, 50, 401, 31))
        self.product2.setStyleSheet("font: 75 10pt \"Leelawadee\";")
        self.product2.setObjectName("product2")
        self.price2 = QtWidgets.QLabel(self.frame_3)
        self.price2.setGeometry(QtCore.QRect(130, 130, 181, 31))
        self.price2.setStyleSheet("font: 75 10pt \"Leelawadee\";")
        self.price2.setObjectName("price2")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(40, 400, 1111, 261))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(30, 50, 1051, 51))
        self.frame_5.setStyleSheet("background-color: rgb(241, 245, 244);\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.rec1 = QtWidgets.QLabel(self.frame_5)
        self.rec1.setGeometry(QtCore.QRect(20, 10, 1011, 31))
        self.rec1.setStyleSheet("font: 75 10pt \"Leelawadee\";")
        self.rec1.setObjectName("rec1")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setGeometry(QtCore.QRect(30, 120, 1051, 51))
        self.frame_6.setStyleSheet("background-color: rgb(241, 245, 244);\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.rec2 = QtWidgets.QLabel(self.frame_6)
        self.rec2.setGeometry(QtCore.QRect(20, 10, 1011, 31))
        self.rec2.setStyleSheet("font: 75 10pt \"Leelawadee\";")
        self.rec2.setObjectName("rec2")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setGeometry(QtCore.QRect(30, 190, 1051, 51))
        self.frame_7.setStyleSheet("background-color: rgb(241, 245, 244);\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_15 = QtWidgets.QLabel(self.frame_7)
        self.label_15.setGeometry(QtCore.QRect(20, 10, 1011, 31))
        self.label_15.setStyleSheet("font: 75 10pt \"Leelawadee\";")
        self.label_15.setObjectName("label_15")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(40, 10, 181, 31))
        self.label_4.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 20, 381, 51))
        self.label.setStyleSheet("font: 28pt \"STHupo\";")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1205, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.search_button.clicked.connect(self.button_clicked)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_bar.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Amazon Pantry"))
        self.label_5.setText(_translate("MainWindow", "Product :"))
        self.label_6.setText(_translate("MainWindow", "Price :"))
        self.product1.setText(_translate("MainWindow", "product..."))
        self.price1.setText(_translate("MainWindow", "price..."))
        self.label_3.setText(_translate("MainWindow", "Grofers"))
        self.label_7.setText(_translate("MainWindow", "Product :"))
        self.label_8.setText(_translate("MainWindow", "Price :"))
        self.product2.setText(_translate("MainWindow", "product..."))
        self.price2.setText(_translate("MainWindow", "price..."))
        self.rec1.setText(_translate("MainWindow", "recommended..."))
        self.rec2.setText(_translate("MainWindow", "recommended..."))
        self.label_15.setText(_translate("MainWindow", "recommended..."))
        self.label_4.setText(_translate("MainWindow", "Recommendation:"))
        self.label.setText(_translate("MainWindow", "The Online Depot"))

    def button_clicked(self):
        print("clicked")
        self.get_text = self.search_bar.toPlainText()
        compare = price_comparison.PriceComparison(self.get_text)
        list_of_title_and_prices = compare.display()
        print(list_of_title_and_prices)
        if self.get_text != "":
            self.product1.setText(list_of_title_and_prices[0][0])
            self.product2.setText(list_of_title_and_prices[1][0])
            self.price1.setText(list_of_title_and_prices[0][1])
            self.price2.setText(list_of_title_and_prices[1][1])
        val = return_users(self.get_text)
        print(val[0], val[1])
        re = GroceryRecommendation(val[0], val[1])
        list_of_recommended_products = re.get_recommendation()
        print(list_of_recommended_products)
        self.rec1.setText(list_of_recommended_products[0])
        self.rec2.setText(list_of_recommended_products[1])
        self.label_15.setText(list_of_recommended_products[2])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
